### ISSUE TITLE
Charts are beeing removed

### ISSUE THREAD

**Issue by ju-bezdek** [optimistex/xlsx-template-ex#6]
After processing template all charts are being removed from excel.

**Comment by optimistex** [comment]
@ju-bezdek The component based on https://github.com/exceljs/exceljs and just extend it to make the templates.
So, try to find a solution for exceljs. In case you find make a pull request, or share a link to a solution and I'll try to add a support.

Close the issue because it depends from third party component.

**Comment by ju-bezdek** [comment]
Sorry to hear that. I tried [optilude/xlsx-template](https://github.com/optilude/xlsx-template) as well and it works fine, but I like your syntax more.

**Comment by optimistex** [comment]
@ju-bezdek https://github.com/exceljs/exceljs only one library that I've found with support inserting images images (it was critical for me).
If you'll find a solution than welcome to improve the library.
